name: Update GitHub Trophies

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Generate GitHub Trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          username: heisenberg-611
          output_path: profile/trophy.svg
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Commit generated file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/trophy.svg
          git commit -m "Update GitHub trophies" || exit 0
          git push
